### ISSUE TITLE
Website throws TypeError when choosing City source as Region Row

### ISSUE THREAD

**Issue by anthonyma94** [benkeen/generatedata#705]
When I choose the following options for cities:
![image](https://user-images.githubusercontent.com/52266992/141184458-baa40cf8-9c01-464d-93c3-f41c514f9c46.png)

The data fails to generate and the site throws the following error:
![image](https://user-images.githubusercontent.com/52266992/141184557-ffe2f781-a60d-470c-be62-78a931651f8f.png)

This also happens with postal code/zip.

This happens whether cities row is above or below region row.

**Comment by benkeen** [comment]
Hi @anthonyma94, thanks for the bug report! 

I tried reproducing it but no luck yet. From the error you showed, it's clearly a bug. A few questions:
- what browser & OS are you using? 
- were you using an existing data set you created earlier, or does this occur with a totally new data set as well (i.e. try clearing the page then adding them again - same problem?) 
- in your console, do you see any requests that failed to load? Or just this error?

**Comment by benkeen** [comment]
I can reproduce it now. I found I had to play with the region field. I'll look at this shortly, thanks again @anthonyma94!

**Comment by benkeen** [comment]
Hey @anthonyma94, mind checking it again now? I just deployed the fix.

**Comment by anthonyma94** [comment]
@benkeen sorry for the late reply. Looks like the bug is still there. My region is set to Countries -> Canada, Short format, and my city is set to Region Row -> Row 1. I tested it in Incognito mode to make sure no caching was involved.

**Comment by benkeen** [comment]
Hmm, thanks so much. The exact same error occurs? That's really very odd..  I just tried that scenario with Mac/latest Chrome & no problems. 

I'll take another look at this after work.

**Comment by benkeen** [comment]
Apologies @anthonyma94, I see the problem again now. Seems like I didn't solve all cases. 😊

**Comment by benkeen** [comment]
Fiddly one. The new problem was that the comparison check for finding the appropriate display value failed when you were using shortcodes for the Region field. I'll update the prod site this weekend. Thanks again for your help + patience!
